# Generated by Django 6.1.1 on 2026-09-03 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarhetaaccount',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='bio',
            field=models.TextField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='card_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='card_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='card_theme',
            field=models.CharField(default='paper', max_length=20),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='card_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tarhetaaccount',
            name='socials',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
