# Generated by Django 6.1.1 on 2026-09-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_tarhetaaccount_avatar_url_tarhetaaccount_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarhetaaccount',
            name='avatar_url',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
