# Generated by Django 6.1.1 on 2026-09-03 16:49

import json

from django.db import migrations, models


def convert_legacy_socials(apps, schema_editor):
    Account = apps.get_model('hub', 'TarhetaAccount')
    for account in Account.objects.all().iterator():
        legacy_socials = (account.socials or '').strip()
        account.socials = json.dumps([{'platform': 'other', 'handle': legacy_socials}]) if legacy_socials else '[]'
        account.save(update_fields=['socials'])


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_tarhetaaccount_avatar_url'),
    ]

    operations = [
        migrations.RunPython(convert_legacy_socials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tarhetaaccount',
            name='socials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
