# Generated by Django 6.1.1 on 2026-09-03 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_tarhetaaccount_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('media', 'Video')], default='link', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('destination', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='hub.tarhetaaccount')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
