# Generated by Django 6.1.1 on 2026-09-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_hubcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubcard',
            name='image',
            field=models.ImageField(blank=True, upload_to='cards/'),
        ),
    ]
