# Generated by Django 6.1.1 on 2026-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_hubcard_function_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubcard',
            name='kind',
            field=models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('video', 'Video'), ('audio', 'MP3'), ('schedule', 'Class schedule'), ('media', 'Video')], default='link', max_length=10),
        ),
    ]
